from tkinter import *
root = Tk()
root.title("Registration Form")
root.geometry("400x400")
Label(root, text="Registration Form", font=("Arial", 16)).grid(row=0, column=1)
Label(root, text="Name").grid(row=1, column=0)
Label(root, text="Email").grid(row=2, column=0)
Label(root, text="Phone").grid(row=3, column=0)
Label(root, text="Password").grid(row=4, column=0)
Label(root, text="Gender").grid(row=5, column=0)
name = Entry(root)
email = Entry(root)
phone = Entry(root)
password = Entry(root, show="*")
name.grid(row=1, column=1)
email.grid(row=2, column=1)
phone.grid(row=3, column=1)
password.grid(row=4, column=1)
gender = StringVar()
Radiobutton(root, text="Male", variable=gender, value="Male").grid(row=5, column=1)
Radiobutton(root, text="Female", variable=gender, value="Female").grid(row=5, column=2)
def register():
    print("Name:", name.get())
    print("Email:", email.get())
    print("Phone:", phone.get())
    print("Password:", password.get())
    print("Gender:", gender.get())
Button(root, text="Register", command=register).grid(row=6, column=1)
root.mainloop()